simulation:
  duration: 1000  # time slots
  area_size: [1000, 1000]  # meters
  
vehicles:
  mission_vehicles: 30
  collaborative_vehicles: 20
  speed_range: [30, 120]  # km/h
  communication_range: 250  # meters
  
infrastructure:
  rsus: 5
  edge_servers: 5
  bandwidth: 20  # MHz
  subchannel_bandwidth: 1  # MHz
  
tasks:
  data_size_range: [0.3, 0.45]  # MB
  computation_demand_range: [0.3, 0.45]  # GHz
  
services:
  total_services: 10
  zipf_parameter: 0.8
  
algorithms:
  cuckoo:
    nest_size: 25
    max_iterations: 100
    discovery_probability: 0.25
    step_size_factor: 1.0
    levy_beta: 1.5
  differential_evolution:
    scaling_factor: 0.5
    crossover_probability: 0.9